name: Create EAS Update Preview
on:
  pull_request:

jobs:
  preview:
    name: Create preview
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: expo/expo-github-action/preview@v8
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          command: eas update --auto
